### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by whichxjy** [gsoc-cn/gsoc-cn#101]
Hi there! I got selected for GSoC with Mozilla in 2020. My project is [bikeshed-rs](https://summerofcode.withgoogle.com/archive/2020/projects/4824688972267520/). I'd like to contribute to this repo.

**Comment by gaocegege** [comment]
You've invited whichxjy to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.
