### ISSUE TITLE
这里有一个GSoC交流群，想申请添加到gsoc-cn的readme中。

### ISSUE THREAD

**Issue by erdengk** [gsoc-cn/gsoc-cn#104]
您好，我是一名想要申请2022GSoC的大学生，我发现readme中的QQ群被移除，猜测是群不再维护了，我建立了一个QQ群用来交流，想申请添加到gsoc-cn的readme中，目前群里有10位同学。也期待您能加入群中共同管理，我能够保证我会认真维护此群。希望得到您的答复。
QQ群号：621656169

**Comment by MikeLing** [comment]
@gaocegege @geekplux @zhaoqxu-eth

**Comment by gaocegege** [comment]
LGTM

**Comment by geekplux** [comment]
LGTM，果然 GenZ 都用 QQ

**Comment by gaocegege** [comment]
本 GenZ 也要开始用 QQ 了！

**Comment by gaocegege** [comment]
@erdengk Please open a PR to add the new QQ group into README.

**Comment by erdengk** [comment]
> @erdengk Please open a PR to add the new QQ group into README.

ok，thanks

**Comment by gaocegege** [comment]
https://github.com/gsoc-cn/gsoc-cn/pull/105
