### ISSUE TITLE
申请添加新的Slack链接

### ISSUE THREAD

**Issue by erdengk** [gsoc-cn/gsoc-cn#111]
各位前辈好，我是今年入选GSoC2022的同学。我去年在仓库中添加了QQ群并与其他小伙伴一同维护 #104 。
经过一年的沉淀，现在群里已经有290名喜欢开源，对GSoC感兴趣的小伙伴。

![image](https://user-images.githubusercontent.com/37730787/169678274-af111bb6-6139-41aa-8071-e5051d52d0ae.png)

这是群内今年申请状态的统计图（截止2022.5.22）

![image](https://user-images.githubusercontent.com/37730787/169678332-2daaf0b6-d939-43c3-a61d-1beceae741ab.png)

**中选学生大部分都是第一次参加GSoC，对于中选之后的事情不知道如何安排，于是我们建立了一个slack空间用来商讨此事，也想借着这次机会将这些流程、经验总结出来，供之后申请的同学参考。**

目前slack空间中有两个频道，一个是公共频道，一个是中选学生频道。

**我注意到README中的slack链接已经失效。可否将上面提到的slack添加到README中？**

这是[邀请链接](https://join.slack.com/t/gsoc--cn/shared_invite/zt-19dzoxlc5-p7D0G9pkSEqsgx9WtxtUFw)

**Comment by MikeLing** [comment]
诶，之前的居然失效了，成为社畜后我真的太久没有登过slack了😓。
替换失效的slack我完全OK，只是得去看看失效的原因，因为之前还有不少同学在里面（虽然很大一部分都加了微信群（
@gaocegege 和 @geekplux 怎么看？

**Comment by MikeLing** [comment]
BTW，@erdengk 可以提交一个替换的pr 然后link到这个issue，我们直接在pr里讨论吧

**Comment by geekplux** [comment]
可以啊，之前的 Slack 我都好久没看过，可能 Slack 群组的最后结局都是疏于维护 👀
等 @erdengk 的 PR 吧

**Comment by erdengk** [comment]
@geekplux @MikeLing 前辈们，我已提交pr，欢迎讨论

**Comment by MikeLing** [comment]
PR已经merge了，这个issue我就关啦～
