### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by pchengma** [gsoc-cn/gsoc-cn#115]
I am a student selected for GSoC 2022 with Apache EventMesh. 

The GSoC project I am working on is [Apache EventMesh Support Knative as Eventing Infra](https://summerofcode.withgoogle.com/programs/2022/projects/YxBHSLin). 

I'd like to contribute to this organization. Thanks very much!

**Comment by geekplux** [comment]
invitation sent, good job
