### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by greenhandatsjtu** [gsoc-cn/gsoc-cn#119]
Hi, I'm a GSoC 2022 mentee, [this](https://summerofcode.withgoogle.com/programs/2022/projects/PQWj3424) is my project.

**Comment by gaocegege** [comment]
You've invited greenhandatsjtu to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.
