### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by RandyLambert** [gsoc-cn/gsoc-cn#125]
Hi, I am selected in GSoC 2022. I am a student working on CNCF chaos-mesh

My project is [RPC cross different namespaces through unix socket](https://summerofcode.withgoogle.com/programs/2022/projects/dFZyvm9F)

**Comment by gaocegege** [comment]
> You've invited shouxunsun to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.
