### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by yihuajack** [gsoc-cn/gsoc-cn#126]
I am a student who worked on [`sootty`](https://github.com/Ben1152000/sootty) project "Enhancing the Sootty Terminal-based Graphical Waveform Viewer" of the Free and Open Source Silicon Foundation

My project is [https://summerofcode.withgoogle.com/projects/#6008675886956544](https://summerofcode.withgoogle.com/archive/2022/projects/Pquk5CIB)

**Comment by gaocegege** [comment]
You've invited Liu Yihua to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.

**Comment by gaocegege** [comment]
Welcome!
