### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by seriouszyx** [gsoc-cn/gsoc-cn#127]
I am a GSoC '22 student and my project is [here](https://summerofcode.withgoogle.com/programs/2022/projects/ev4TPeRU).

**Comment by seriouszyx** [comment]
Hi~ @gaocegege @geekplux @MikeLing

**Comment by gaocegege** [comment]
> You've invited Yixiang Zhao to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.  


Sorry for the late reply! I already invited you.
