### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by mqliang** [gsoc-cn/gsoc-cn#13]
I am a student working on Opentracing project. My project is https://summerofcode.withgoogle.com/archive/2017/projects/5449224187543552/

**Comment by MikeLing** [comment]
@mqliang would you mind to add your proposal into https://github.com/gsoc-cn/gsoc-cn/tree/master/resources/proposals/2017? Thanks a lot :)

**Comment by mqliang** [comment]
will do in couple of days.
