### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by skyleaworlder** [gsoc-cn/gsoc-cn#131]
I'm a student working for [FluxML](https://github.com/FluxML).

My project is [Benchmark tooling for common models and operations](https://summerofcode.withgoogle.com/programs/2023/projects/whO3fAS8) and I created #129 three months ago.

**Comment by gaocegege** [comment]
> You've invited Jiageng to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.
