### ISSUE TITLE
GSoC'18 安利计划讨论

### ISSUE THREAD

**Issue by gaocegege** [gsoc-cn/gsoc-cn#15]
是不是要宣传一波，以某种方式

**Comment by tonghuix** [comment]
大力支持一下！

**Comment by Luolc** [comment]
一个想法：每个人有空的时候可以写个短几百字的简介介绍一下自己参与过的项目，大概有什么基本要求呀 mentor 的喜好啊或者随便什么的，咱们在申请的时候弄个合集

**Comment by gaocegege** [comment]
@Luolc 

https://github.com/gsoc-cn/gsoc-cn/issues/7

**Comment by OXPHOS** [comment]
可以setup一下github.io

**Comment by gaocegege** [comment]
> 一个想法：每个人有空的时候可以写个短几百字的简介介绍一下自己参与过的项目，大概有什么基本要求呀 mentor 的喜好啊或者随便什么的，咱们在申请的时候弄个合集

不如在 resources 目录下建立 orgs 目录，每个 org 对应一个 Markdown 文件，在 README 里贴上 orgs 目录下的 README 链接，如何

**Comment by geekplux** [comment]
我觉得可以，还可以 link 到每个组织当年的 proposal issue 里

**Comment by MikeLing** [comment]
是时候把 @Luolc 当时写的知乎文章拿出来分享了
