### ISSUE TITLE
[discussion] freenode or gitter

### ISSUE THREAD

**Issue by gaocegege** [gsoc-cn/gsoc-cn#16]
freenode 是不是有点太重，轻量级的 gitter 是不是更好

**Comment by MikeLing** [comment]
slack也可以的

**Comment by tonghuix** [comment]
IRC 略老旧，不适合传图不适合当代移动互联时代，对纯新手有一定的门槛。
Slack 不开源不自由，现在使用的社区并不多
其他可选方案还有：[Riot.im](https://riot.im)（Matrix协议）、[Mattermost](https://about.mattermost.com/)、[Zulip](https://zulipchat.com/)（去年参加了GSoC）、Rocket.chat、[Movim](https://movim.eu/)（XMPP协议网页客户端）等

我个人推荐 **Riot,im**，平时我就在用，还能连到 IRC 服务器，支持 markdown 语法，不需要自己搭服务器，可以用matrix的服务器也可以连其他第三方服务。这种“联邦式”（federation）去中心化服务更方便。这里有个教程 https://vimacs.lcpu.club/matrix-guide/

**Comment by geekplux** [comment]
telegram，slack 被 GFW 了。
Riot.im 当时我们 org 用的就是这个，挺好的，除了稍微有点小众，Mattermost 类似。

*IM 我们用的很少吧，咱们的两个微信群都鲜有人说话。这个 issue 的目的是让新人有询问沟通的工具？*

**Comment by gaocegege** [comment]
我觉得是的，主要是有个方便的渠道来交流，gitter 比较好的一点是不需要登陆也能看到对话，是这样来着么

**Comment by geekplux** [comment]
我也觉得 gitter 就挺好

**Comment by tonghuix** [comment]
确实，就gitter这挺好。先 close 了。
