### ISSUE TITLE
在主页README添加一个Contribution的subtitle

### ISSUE THREAD

**Issue by Luolc** [gsoc-cn/gsoc-cn#17]
建议在主页 README 比较靠前位置添加一个 Contribution 的 subtitle，issue 要点进去一点点翻，现在怎么来做贡献我自己还是挺不清楚的，要去查 closed 的 issue 才能了解（之前关注不多），对贡献者有点门槛。

很多开源项目都是主页写了 Contribution 方式，或者引导到相应的 wiki，咱们可以加上类似的

**Comment by geekplux** [comment]
PR welcome 🤓
