### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by blackskygg** [gsoc-cn/gsoc-cn#18]
I am a student working on the Xen Project. My project is https://summerofcode.withgoogle.com/archive/2017/projects/5356246735519744/

And I've authored a [blog post](https://blog.xenproject.org/2017/08/29/my-gsoc-experience-allow-setting-up-shared-memory-regions-between-vms-from-xl-config-file/) about my GSoC experience.

**Comment by gaocegege** [comment]
@blackskygg 你好，我已经邀请你了，友情提醒一句，少熬夜，保重身体 :0

> You've invited Zhongze Liu to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.
