### ISSUE TITLE
Which LICENSE?

### ISSUE THREAD

**Issue by geekplux** [gsoc-cn/gsoc-cn#3]
Which LICENSE should we choose?

**Comment by MikeLing** [comment]
BSD?

**Comment by mirca** [comment]
I would say MIT is more appropriate

**Comment by gaocegege** [comment]
Maybe [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/3.0/deed.zh) is more appropriate since there is no code, just articles.

**Comment by geekplux** [comment]
@gaocegege I agree
