### ISSUE TITLE
[Join Request] Wang Yihang from HIT work on Metasploit

### ISSUE THREAD

**Issue by WangYihang** [gsoc-cn/gsoc-cn#34]
Hi, I am a student working on Metasploit project in GSoC 2018 from Harbin Institute of Techology. Studying Cyber Security.

My project is 
> [Add meta-shell command for Meterpreter](https://summerofcode.withgoogle.com/dashboard/project/5322546648449024/overview/)

Very glad to meet you guys~ 
:D

Name: Wang Yihang
Email: wangyihanger@gmail.com
GitHub: https://github.com/wangyihang

**Comment by gaocegege** [comment]
Invited, Welcome to the community!
