### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by demerzel1** [gsoc-cn/gsoc-cn#40]
Hi.
I am a student working for Stony Brook University Biomedical Informatics in GSoC2018.
My project is [https://summerofcode.withgoogle.com/projects/#6093833721348096](url)

**Comment by gaocegege** [comment]
Welcome! :tada: 

I sent you an invitation :smile:

**Comment by gaocegege** [comment]
Invitations are sent via email and can be accepted at https://github.com/gsoc-cn
