### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by NutshellySima** [gsoc-cn/gsoc-cn#42]
Hello, 
I am a student working for LLVM Compiler Infrastructure in GSoC 2018, 
My project is https://summerofcode.withgoogle.com/projects/#6008736125026304

**Comment by gaocegege** [comment]
You've invited Chijun Sima to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.

**Comment by gaocegege** [comment]
Welcome! :tada:
