### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by gaocegege** [gsoc-cn/gsoc-cn#6]
I am a student working on Processing project, ...

My project is [github.com/gaocegege/Processing.R](https://github.com/gaocegege/Processing.R), and I am the author of [Google Summer of Code 学生申请指南](https://zhuanlan.zhihu.com/p/27823910)

PS: 为什么都是 cn 还要用英文发 issue。。

**Comment by gaocegege** [comment]
Thanks for the invitation.

**Comment by MikeLing** [comment]
> PS: 为什么都是 cn 还要用英文发 issue。。

其实我上次和@geekplux 讨论过这个问题，可是大家都是惯性的用英文。其实中英文随机就好啦~
