### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by jiachengxu** [gsoc-cn/gsoc-cn#63]
Hi guys,

My name is Jiacheng Xu, and I took part in GSoC 2018 and worked on CoreDNS in CNCF. Happy to meet all you guys!

Thanks

**Comment by gaocegege** [comment]
Welcome, invite sent.

**Comment by jiachengxu** [comment]
Thanks!

**Comment by gaocegege** [comment]
I assigned this issue to you: https://github.com/gsoc-cn/gsoc-cn/issues/20

I'd appreciate it if you can write an introduction to your project and CNCF.

**Comment by jiachengxu** [comment]
Ok, will do that! Thanks!
