### ISSUE TITLE
[Feature Request] Introduction to organizations

### ISSUE THREAD

**Issue by gaocegege** [gsoc-cn/gsoc-cn#7]
We have a lot of participants worked for different organizations, so I think we could introduce the organizations to the readers.

**Comment by MikeLing** [comment]
Hey! Thanks for open this issue  \o/

The readers? You mean the students who want to join GSoC 2018 or?

**Comment by gaocegege** [comment]
是的，就是介绍下每个 org 是怎么沟通的，有什么特点特色，偏好什么类型的申请等等

**Comment by geekplux** [comment]
这个我觉得只要有人愿意分享当然可以。不过针对具体 org 的参考意义可能比较小，万一这些 org 明年不中呢。我觉得还是提一些普适性的建议比较好。

**Comment by gaocegege** [comment]
嗯，仅供参考吧，我个人觉得普适性的肯定是必须有的，如果有针对 org 的，申请难度会大大降低。。

**Comment by geekplux** [comment]
同意

**Comment by MikeLing** [comment]
mmm, 普适性的建议啊，我记得Google的学生手册上有写http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/ 还有很多英文博客http://teom.org/blog/kde/how-to-write-a-kick-ass-proposal-for-google-summer-of-code/。 但是中文的我倒真的没有发现，也许能有个翻译文档的环节？

**Comment by gaocegege** [comment]
这个 repo 只关注 proposal 的写作么，那之前的申请准备怎么说呢

**Comment by geekplux** [comment]
对申请机制和奖励机制的可以再阐述一下，现在只在 [resources](./resources) 里介绍了一点。

**Comment by MikeLing** [comment]
这里有篇中文的博文 https://linuxtoy.org/archives/from-bug-reporter-google-summer-code.html 还有就是当时@Luolc 写的这篇文章。

ps: 我感觉@geekplux写的这个README https://github.com/gsoc-cn/gsoc-cn/blob/master/resources/README.md 完全可以用作GSoC这个repo的README。感觉比单调的一行字要生动的多

**Comment by gaocegege** [comment]
嗯我也觉得，现在的 readme 比较有迷惑性

**Comment by MikeLing** [comment]
> 嗯我也觉得，现在的 readme 比较有迷惑性

那我就把它挪过去啦
