### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by huangyz0918** [gsoc-cn/gsoc-cn#77]
I am a student working on [Open Data Kit](https://opendatakit.org/) project, I'd like to contribute to this organization.

My project is https://summerofcode.withgoogle.com/projects/#5895284922515456

**Comment by gaocegege** [comment]
> You've invited Yizheng Huang to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation. 

Welcome! If you have time, please have a look at #20

**Comment by huangyz0918** [comment]
Cool, will do that.
