### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by WenheLI** [gsoc-cn/gsoc-cn#80]
I am a student working on TensorFlow.js, I'd like to contribute to this organization.

My project is https://summerofcode.withgoogle.com/projects/#5627483175518208

**Comment by mincong-h** [comment]
Could you follow the contribution guide: https://github.com/gsoc-cn/gsoc-cn/issues/20?

**Comment by WenheLI** [comment]
@mincong-h - Will do, thanks!

**Comment by WenheLI** [comment]
@mincong-h - Add a draft intro.
See #81

**Comment by mincong-h** [comment]
Do you have access now? cc @gaocegege @geekplux @MikeLing @OXPHOS @xuzhaoqing

**Comment by WenheLI** [comment]
@mincong-h - Still no access~

**Comment by gaocegege** [comment]
>  You've invited WenheLI to gsoc-cn! They'll be receiving an email shortly. They can also visit https://github.com/gsoc-cn to accept the invitation.

Thanks for your contribution!
