### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by huxuan** [gsoc-cn/gsoc-cn#83]
I was a student working on GNOME project in 2013. It is great to see GSOC-CN has a Github Community now.

My project is [Porting GTG and Liblarch to Gtk3 and Python3](https://www.google-melange.com/archive/gsoc/2013/orgs/gnome/projects/huxuan.html).

**Comment by jiachengxu** [comment]
Welcome 👍 
Can you please follow the contribution guide here: #20 ?

**Comment by huxuan** [comment]
@jiachengxu Gotcha, will do it later.

**Comment by gaocegege** [comment]
@huxuan Invited you as a member of the org, welcome. And please help us about #20
