### ISSUE TITLE
Hyperledger Mentorship Program

### ISSUE THREAD

**Issue by gaocegege** [gsoc-cn/gsoc-cn#84]
> Hyperledger 项目的话应该是新建一个repo还是直接加在这边？　\cc @gaocegege
> 
> [2020年的项目列表](https://wiki.hyperledger.org/display/INTERN/2020+Projects)

我个人更倾向于一个新的 repo，你觉得呢

**Comment by gaocegege** [comment]
@dexhunter

**Comment by dexhunter** [comment]
可以的:ok_man:

**Comment by dexhunter** [comment]
我在自己这建个repo fork到这边还是直接在这边建立repo?

**Comment by gaocegege** [comment]
直接创建吧

**Comment by dexhunter** [comment]
> 直接创建吧

需要把我加进来 :rofl:

**Comment by dexhunter** [comment]
https://github.com/gsoc-cn/hyperledger-mentor-program
