### ISSUE TITLE
现在可以查看2020GSOC项目列表吗

### ISSUE THREAD

**Issue by liwen-tj** [gsoc-cn/gsoc-cn#85]
我在这里看到 https://opensource.googleblog.com/ 项目已经确定了。
但是，官网进去却说我需要重新注册账号，注册账号3月16号才开放。

请问我怎么能够看到今年的项目列表呢？

**Comment by gaocegege** [comment]
项目列表是什么

https://summerofcode.withgoogle.com/organizations/ 么

**Comment by liwen-tj** [comment]
就是今年的可以选的项目介绍

**Comment by liwen-tj** [comment]
> 项目列表是什么
> 
> https://summerofcode.withgoogle.com/organizations/ 么

这个似乎只是组织，没有具体到项目

**Comment by gaocegege** [comment]
项目要到每个 org 自己的 idea list 下去看，不同 org 有自己的 list 页面，没有统一的。

**Comment by geekplux** [comment]
@liwen-tj 项目还没确定，但每个org应该都已经定的七七八八了，如果你的proposal写的很出彩，说不定就可以做你想做的项目了。

**Comment by gaocegege** [comment]
嗯有些 org 可以自己提 idea 的，暂时先关闭了，如果还有问题欢迎回复

**Comment by liwen-tj** [comment]
> 项目要到每个 org 自己的 idea list 下去看，不同 org 有自己的 list 页面，没有统一的。

好的，我去找找，谢谢🙏了
