### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by LovelyBuggies** [gsoc-cn/gsoc-cn#86]
I am a student in GSoC' 2020. I just received my acceptance letter. My project is [Hist: histogramming for analysis powered by boost-histogram](https://summerofcode.withgoogle.com/dashboard/project/6253271695491072/overview/). This repo gave me a great deal of help, so I want to feed back to it. Thanks!

**Comment by mincong-h** [comment]
Hi @LovelyBuggies , congratulations! Could you follow the guide line here: https://github.com/gsoc-cn/gsoc-cn/issues/20?

**Comment by LovelyBuggies** [comment]
I am a student working on Hist project, which is in CERN-PSF org.

My project is https://summerofcode.withgoogle.com/projects/#6253271695491072.

My email is ninomyemail@gmail.com

**Comment by LovelyBuggies** [comment]
@mincong-h @gaocegege Is it okay?

**Comment by gaocegege** [comment]
> You've invited 1 member. They'll receive their invitation email shortly.
