### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by MRNIU** [gsoc-cn/gsoc-cn#88]
I am a student working on [Arduino](https://arduino.cc) project.

My project is [https://summerofcode.withgoogle.com/projects/#6482418854264832](https://summerofcode.withgoogle.com/projects/#6482418854264832).

Thank you.

**Comment by gaocegege** [comment]
> You've invited 1 member. They'll receive their invitation email shortly.

Please have a look at #20

**Comment by mincong-h** [comment]
We may need to update the doc https://github.com/gsoc-cn/gsoc-cn/blob/master/invitation.md
