### ISSUE TITLE
generate-resource-readme.py is not adapt macOS X

### ISSUE THREAD

**Issue by MRNIU** [gsoc-cn/gsoc-cn#90]

**Comment by MRNIU** [comment]
It cannot exclude `.DS_Store`, which is a file that the system generates by default.

**Comment by MRNIU** [comment]
I will fix this in the few days.

**Comment by LovelyBuggies** [comment]
.DS_Store is really a headache, I manually remove it everytime (I found gitignore doesn't work).

**Comment by LovelyBuggies** [comment]
@MRNIU I have fixed it. Travis CI's fail is not related to operating systems. It's because you have lowercase arduino in resource/README.md but have uppercase Arduino folder. GitHub doesn't detect that, so I rm -r arduino first and add again.

**Comment by MRNIU** [comment]
I thought we may remove it by the .py script.
Just like “if uname==Darwin than remove XXX”.

**Comment by MRNIU** [comment]
Hey, I have fix that, may I open a new PR?

**Comment by LovelyBuggies** [comment]
> Hey, I have fix that

ignore .DS_Store?

**Comment by MRNIU** [comment]
```
def parse(self):
        result = []
        for filename in os.listdir(self.resource_path):
            if filename.endswith(".md"):
                continue
            if sys.platform == "darwin" and filename == ".DS_Store":
                continue
            else:
                result.append(filename)
        result.sort(key=lambda v: v.upper())
        return result
```
Worked fine on my machine.

**Comment by LovelyBuggies** [comment]
Nice!

**Comment by gaocegege** [comment]
OK, never test it in MacOS. Actually I hate MacOS.
